import '~/styles/globals.css';
import { cn } from '~/lib/utils';
import localFont from 'next/font/local';

import { GeistSans } from 'geist/font/sans';
const dune = localFont({
  src: '../../public/Dune_Rise.ttf',
  variable: '--font-dune',
});

const grotesque = localFont({
  src: '../../public/Rebond Grotesque Bold.otf',
  variable: '--font-grotesque',
});

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

import { Footer, Navbar } from '~/components';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='!dark'>
      <body
        className={cn(
          'bg-background text-white',
          GeistSans.className,
          dune.variable,
          grotesque.variable
        )}
      >
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
