import '~/styles/globals.css';
import { cn } from '~/lib/utils';
import localFont from 'next/font/local';

import { GeistSans } from 'geist/font/sans';
export const dune = localFont({
  src: '../../public/Dune_Rise.ttf',
  variable: '--font-dune',
});

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={cn('', GeistSans.className, dune.variable)}>
        {children}
      </body>
    </html>
  );
}
